  408  PWD
  409  cd desktop
  410  cd testrepo
  411  git pull origin main
  412  git status
  413  git add *
  414  git commit -m "edited"
  415  git status
  416  git push origin main
  417  git add *
  418  git commit -m "updated from local repo"
  419  git push origin main
  420  git pull origin main
  421  vim calculation.c
  422  touch mp
  423  vim mp
  424  vim mp
  425  git add *
  426  git commit -m "updated from local repo"
  427  git push origin main
  428  git history
  429  history
